//! Grammar to Rust parser code generator.
//!
//! Transforms FMPL grammar patterns into Rust parsing functions.

use crate::error::Result;
use crate::grammar::{CharRange, Grammar, Pattern, Rule};
use crate::pattern::{CharPattern, RepeatKind};
use smol_str::SmolStr;
use std::collections::HashSet;

/// Generate a complete Rust parser module from a grammar.
pub fn generate_parser(grammar: &Grammar) -> Result<String> {
    let mut generator = GrammarToRust::new();
    generator.generate(grammar)
}

/// Generate just the parsing functions, without module wrapper.
pub fn generate_functions(grammar: &Grammar) -> Result<String> {
    let mut generator = GrammarToRust::new();
    generator.generate_functions(grammar)
}

struct GrammarToRust {
    /// Rules already generated (to avoid duplicates)
    generated_rules: HashSet<SmolStr>,
}

impl GrammarToRust {
    fn new() -> Self {
        Self {
            generated_rules: HashSet::new(),
        }
    }

    /// Generate complete parser module
    fn generate(&mut self, grammar: &Grammar) -> Result<String> {
        let mut output = String::new();

        // Module header
        // Note: This code is included into parser.rs via include!()
        // The parent module (parser.rs) already imports:
        // - use crate::ast::*;
        // - use crate::error::{Error, Result};
        // - use crate::lexer::{SpannedToken, Token};
        // - use smol_str::SmolStr;
        // So we DON'T add those imports here.
        output.push_str(&format!(
            "// Generated parser for grammar: {}\n",
            grammar.name
        ));
        output.push_str("// DO NOT EDIT - generated by grammar_to_rust\n");
        output.push_str(
            "// This file is included into parser.rs, imports are inherited from there.\n\n",
        );

        // Additional imports that parser.rs doesn't have
        output.push_str("use crate::value::Value;\n");
        output.push_str("use std::sync::Arc;\n\n");

        // Parse result type
        output.push_str("type ParseResult<T> = Result<(T, usize)>;\n\n");

        // Generate rule functions
        output.push_str(&self.generate_functions(grammar)?);

        // Main entry point
        if grammar.rules.contains_key("code") {
            output.push_str("\n/// Parse FMPL source code (generated parser)\n");
            output.push_str("pub fn generated_parse(source: &str) -> Result<Expr> {\n");
            output.push_str("    match parse_code(source, 0) {\n");
            output.push_str("        Ok((value, _)) => value_to_expr(value),\n");
            output.push_str("        Err(e) => Err(e),\n");
            output.push_str("    }\n");
            output.push_str("}\n\n");

            // Value to Expr conversion (stub for now)
            output.push_str("fn value_to_expr(value: Value) -> Result<Expr> {\n");
            output.push_str("    // TODO: Convert parsed Value to Expr\n");
            output.push_str("    // For now, use legacy parser\n");
            output.push_str(
                "    Err(Error::Runtime(\"value_to_expr not implemented\".to_string()))\n",
            );
            output.push_str("}\n");
        }

        Ok(output)
    }

    /// Generate parsing functions for all rules
    fn generate_functions(&mut self, grammar: &Grammar) -> Result<String> {
        let mut output = String::new();

        for (name, rule) in &grammar.rules {
            if self.generated_rules.contains(name) {
                continue;
            }
            self.generated_rules.insert(name.clone());

            output.push_str(&self.generate_rule_function(name, rule)?);
            output.push('\n');
        }

        Ok(output)
    }

    /// Generate a parsing function for a single rule
    fn generate_rule_function(&self, name: &SmolStr, rule: &Rule) -> Result<String> {
        let fn_name = format!("parse_{}", sanitize_ident(name));
        let body = self.generate_pattern(&rule.pattern)?;

        let mut output = String::new();
        output.push_str(&format!(
            "fn {}(input: &str, pos: usize) -> ParseResult<Value> {{\n",
            fn_name
        ));
        output.push_str(&format!("    {}\n", body));
        output.push_str("}\n");

        Ok(output)
    }

    /// Generate Rust code for a pattern
    fn generate_pattern(&self, pattern: &Pattern) -> Result<String> {
        match pattern {
            Pattern::Empty => Ok("Ok((Value::Null, pos))".to_string()),

            Pattern::Any => Ok(
                "if pos < input.len() {\n\
                     let c = input[pos..].chars().next().unwrap();\n\
                     Ok((Value::String(SmolStr::from_iter([c])), pos + c.len_utf8()))\n\
                 } else {\n\
                     Err(Error::Parser { token: pos, message: \"unexpected end of input\".to_string() })\n\
                 }"
                    .to_string(),
            ),

            Pattern::Char(cp) => match cp {
                CharPattern::Exact(c) => {
                    let char_escaped = escape_char_for_char_literal(*c);
                    let str_escaped = escape_char_for_string_literal(*c);
                    Ok(format!(
                        "if input[pos..].starts_with('{}') {{\n\
                             Ok((Value::String(SmolStr::new(\"{}\")), pos + {}))\n\
                         }} else {{\n\
                             Err(Error::Parser {{ token: pos, message: \"expected '{}'\".to_string() }})\n\
                         }}",
                        char_escaped,
                        str_escaped,
                        c.len_utf8(),
                        str_escaped
                    ))
                }
                CharPattern::Class(ranges) => {
                    let checks: Vec<String> = ranges
                        .iter()
                        .map(|r| match r {
                            CharRange::Char(c) => format!("c == '{}'", escape_char_for_char_literal(*c)),
                            CharRange::Range(lo, hi) => {
                                format!("(c >= '{}' && c <= '{}')", escape_char_for_char_literal(*lo), escape_char_for_char_literal(*hi))
                            }
                        })
                        .collect();

                    Ok(format!(
                        "if pos < input.len() {{\n\
                             let c = input[pos..].chars().next().unwrap();\n\
                             if {} {{\n\
                                 Ok((Value::String(SmolStr::from_iter([c])), pos + c.len_utf8()))\n\
                             }} else {{\n\
                                 Err(Error::Parser {{ token: pos, message: \"character class mismatch\".to_string() }})\n\
                             }}\n\
                         }} else {{\n\
                             Err(Error::Parser {{ token: pos, message: \"unexpected end of input\".to_string() }})\n\
                         }}",
                        checks.join(" || ")
                    ))
                }
                CharPattern::NegatedClass(ranges) => {
                    let checks: Vec<String> = ranges
                        .iter()
                        .map(|r| match r {
                            CharRange::Char(c) => format!("c == '{}'", escape_char_for_char_literal(*c)),
                            CharRange::Range(lo, hi) => {
                                format!("(c >= '{}' && c <= '{}')", escape_char_for_char_literal(*lo), escape_char_for_char_literal(*hi))
                            }
                        })
                        .collect();

                    Ok(format!(
                        "if pos < input.len() {{\n\
                             let c = input[pos..].chars().next().unwrap();\n\
                             if !({}) {{\n\
                                 Ok((Value::String(SmolStr::from_iter([c])), pos + c.len_utf8()))\n\
                             }} else {{\n\
                                 Err(Error::Parser {{ token: pos, message: \"negated character class matched\".to_string() }})\n\
                             }}\n\
                         }} else {{\n\
                             Err(Error::Parser {{ token: pos, message: \"unexpected end of input\".to_string() }})\n\
                         }}",
                        checks.join(" || ")
                    ))
                }
            }

            Pattern::StringLiteral(s) => {
                let escaped = escape_string(s);
                Ok(format!(
                    "if input[pos..].starts_with(\"{}\") {{\n\
                         Ok((Value::String(SmolStr::new(\"{}\")), pos + {}))\n\
                     }} else {{\n\
                         Err(Error::Parser {{ token: pos, message: \"expected \\\"{}\\\"\".to_string() }})\n\
                     }}",
                    escaped,
                    escaped,
                    s.len(),
                    escaped
                ))
            }

            Pattern::ApplyRule(name) => {
                let fn_name = format!("parse_{}", sanitize_ident(name));
                Ok(format!("{}(input, pos)", fn_name))
            }

            Pattern::Seq(patterns) => {
                if patterns.is_empty() {
                    return Ok("Ok((Value::Null, pos))".to_string());
                }

                let mut code = String::new();
                code.push_str("{\n");
                code.push_str("    let mut current_pos = pos;\n");
                code.push_str("    let mut results: Vec<Value> = Vec::new();\n");

                for (i, p) in patterns.iter().enumerate() {
                    let inner = self.generate_pattern(p)?;
                    code.push_str(&format!(
                        "    match {{ let pos = current_pos; {} }} {{\n\
                             Ok((v{}, new_pos)) => {{ results.push(v{}); current_pos = new_pos; }}\n\
                             Err(e) => return Err(e),\n\
                         }}\n",
                        inner, i, i
                    ));
                }

                code.push_str("    Ok((Value::List(Arc::new(results)), current_pos))\n");
                code.push_str("}");
                Ok(code)
            }

            Pattern::Choice(alts) => {
                if alts.is_empty() {
                    return Ok(
                        "Err(Error::Parser { token: pos, message: \"no alternatives\".to_string() })"
                            .to_string(),
                    );
                }

                // Use a closure to contain the choice logic and prevent early returns
                // from escaping the enclosing sequence. Each alternative is tried in order,
                // and the first successful one is returned.
                let mut code = String::new();
                code.push_str("(|| {\n");
                code.push_str("    let start_pos = pos;\n");

                for (i, (alt, _backtracking)) in alts.iter().enumerate() {
                    let inner = self.generate_pattern(alt)?;
                    if i == alts.len() - 1 {
                        // Last alternative - return its result directly
                        code.push_str(&format!("    {{ let pos = start_pos; {} }}\n", inner));
                    } else {
                        // Try this alternative, return if successful
                        code.push_str(&format!(
                            "    let result = {{ let pos = start_pos; {} }};\n",
                            inner
                        ));
                        code.push_str("    if result.is_ok() { return result; }\n");
                    }
                }

                code.push_str("})()");
                Ok(code)
            }

            Pattern::Repeat { pattern: inner, kind } => {
                let inner_code = self.generate_pattern(inner)?;
                match kind {
                    RepeatKind::ZeroOrMore => Ok(format!(
                        "{{\n\
                             let mut results: Vec<Value> = Vec::new();\n\
                             let mut current_pos = pos;\n\
                             loop {{\n\
                                 match {{ let pos = current_pos; {} }} {{\n\
                                     Ok((v, new_pos)) => {{\n\
                                         if new_pos == current_pos {{ break; }}\n\
                                         results.push(v);\n\
                                         current_pos = new_pos;\n\
                                     }}\n\
                                     Err(_) => break,\n\
                                 }}\n\
                             }}\n\
                             Ok((Value::List(Arc::new(results)), current_pos))\n\
                         }}",
                        inner_code
                    )),
                    RepeatKind::OneOrMore => Ok(format!(
                        "{{\n\
                             match {{ let pos = pos; {} }} {{\n\
                                 Ok((first, first_pos)) => {{\n\
                                     let mut results = vec![first];\n\
                                     let mut current_pos = first_pos;\n\
                                     loop {{\n\
                                         match {{ let pos = current_pos; {} }} {{\n\
                                             Ok((v, new_pos)) => {{\n\
                                                 if new_pos == current_pos {{ break; }}\n\
                                                 results.push(v);\n\
                                                 current_pos = new_pos;\n\
                                             }}\n\
                                             Err(_) => break,\n\
                                         }}\n\
                                     }}\n\
                                     Ok((Value::List(Arc::new(results)), current_pos))\n\
                                 }}\n\
                                 Err(e) => Err(e),\n\
                             }}\n\
                         }}",
                        inner_code, inner_code
                    )),
                }
            }

            Pattern::Optional(inner) => {
                let inner_code = self.generate_pattern(inner)?;
                Ok(format!(
                    "match {{ let pos = pos; {} }} {{\n\
                         Ok((v, new_pos)) => Ok((v, new_pos)),\n\
                         Err(_) => Ok((Value::Null, pos)),\n\
                     }}",
                    inner_code
                ))
            }

            Pattern::Lookahead(inner) => {
                let inner_code = self.generate_pattern(inner)?;
                Ok(format!(
                    "match {{ let pos = pos; {} }} {{\n\
                         Ok((v, _)) => Ok((v, pos)),\n\
                         Err(e) => Err(e),\n\
                     }}",
                    inner_code
                ))
            }

            Pattern::Not(inner) => {
                let inner_code = self.generate_pattern(inner)?;
                Ok(format!(
                    "match {{ let pos = pos; {} }} {{\n\
                         Ok(_) => Err(Error::Parser {{ token: pos, message: \"negative lookahead failed\".to_string() }}),\n\
                         Err(_) => Ok((Value::Null, pos)),\n\
                     }}",
                    inner_code
                ))
            }

            Pattern::Bind { pattern: inner, name, is_choice: _ } => {
                let inner_code = self.generate_pattern(inner)?;
                let var_name = sanitize_ident(name);
                Ok(format!(
                    "match {{ let pos = pos; {} }} {{\n\
                         Ok((v, new_pos)) => {{ let {} = v.clone(); Ok((v, new_pos)) }}\n\
                         Err(e) => Err(e),\n\
                     }}",
                    inner_code, var_name
                ))
            }

            Pattern::Action { pattern: inner, action: _ } => {
                // For now, just return the matched value
                // TODO: Compile the action expression to Rust
                let inner_code = self.generate_pattern(inner)?;
                Ok(format!(
                    "match {{ let pos = pos; {} }} {{\n\
                         Ok((v, new_pos)) => Ok((v, new_pos)),\n\
                         Err(e) => Err(e),\n\
                     }}",
                    inner_code
                ))
            }

            Pattern::End => Ok(
                "if pos >= input.len() {\n\
                     Ok((Value::Null, pos))\n\
                 } else {\n\
                     Err(Error::Parser { token: pos, message: \"expected end of input\".to_string() })\n\
                 }"
                    .to_string(),
            ),

            // Patterns not yet implemented
            _ => Ok(format!(
                "Err(Error::Parser {{ token: pos, message: \"pattern not implemented: {:?}\".to_string() }})",
                std::mem::discriminant(pattern)
            )),
        }
    }
}

/// Escape a character for Rust char literal (e.g., 'x', '\\', '\'')
fn escape_char_for_char_literal(c: char) -> String {
    match c {
        '\\' => "\\\\".to_string(),
        '\'' => "\\'".to_string(),
        '\n' => "\\n".to_string(),
        '\r' => "\\r".to_string(),
        '\t' => "\\t".to_string(),
        c => c.to_string(),
    }
}

/// Escape a character for use inside a Rust string literal (e.g., "x", "\\", "\"")
fn escape_char_for_string_literal(c: char) -> String {
    match c {
        '\\' => "\\\\".to_string(),
        '"' => "\\\"".to_string(),
        '\n' => "\\n".to_string(),
        '\r' => "\\r".to_string(),
        '\t' => "\\t".to_string(),
        c => c.to_string(),
    }
}

/// Escape a string for Rust string literal
fn escape_string(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    for c in s.chars() {
        result.push_str(&escape_char_for_string_literal(c));
    }
    result
}

/// Sanitize identifier for Rust
fn sanitize_ident(name: &str) -> String {
    let sanitized = name
        .replace("-", "_")
        .replace("?", "_q")
        .replace("!", "_bang");

    match sanitized.as_str() {
        "type" | "match" | "loop" | "move" | "ref" | "self" | "Self" | "fn" | "let" | "mut"
        | "const" | "static" | "pub" | "mod" | "use" | "as" | "if" | "else" | "while" | "for"
        | "in" | "return" | "break" | "continue" | "struct" | "enum" | "trait" | "impl"
        | "where" | "async" | "await" | "dyn" | "true" | "false" => {
            format!("r#{}", sanitized)
        }
        _ => sanitized,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::grammar::Rule;

    #[test]
    fn test_generate_literal() {
        let generator = GrammarToRust::new();
        let pattern = Pattern::StringLiteral(SmolStr::new("hello"));
        let code = generator.generate_pattern(&pattern).unwrap();
        assert!(code.contains("starts_with"));
        assert!(code.contains("hello"));
    }

    #[test]
    fn test_generate_char_class() {
        let generator = GrammarToRust::new();
        let pattern = Pattern::Char(CharPattern::Class(vec![CharRange::Range('a', 'z')]));
        let code = generator.generate_pattern(&pattern).unwrap();
        assert!(code.contains(">= 'a'"));
        assert!(code.contains("<= 'z'"));
    }

    #[test]
    fn test_generate_rule() {
        let generator = GrammarToRust::new();
        let pattern = Pattern::ApplyRule(SmolStr::new("digit"));
        let code = generator.generate_pattern(&pattern).unwrap();
        assert!(code.contains("parse_digit"));
    }

    #[test]
    fn test_generate_simple_grammar() {
        let mut grammar = Grammar::new(SmolStr::new("test"));
        grammar.add_rule(
            SmolStr::new("digit"),
            Rule::new(Pattern::Char(CharPattern::Class(vec![CharRange::Range(
                '0', '9',
            )]))),
        );

        let mut generator = GrammarToRust::new();
        let code = generator.generate(&grammar).unwrap();

        assert!(code.contains("fn parse_digit"));
        assert!(code.contains("'0'"));
        assert!(code.contains("'9'"));
    }
}
